# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

twoptsbcril <- function(n1, n2, n3, n4, M) {
    .Call('_onemap_twoptsbcril', PACKAGE = 'onemap', n1, n2, n3, n4, M)
}

